FROM ubuntu:18.04
MAINTAINER magno.mabreu@gmail.com

ENV LANG C.UTF-8
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
ENV RTI_HOME=/opt/portico-2.2.0
ENV RTI_RID_FILE=/opt/portico-2.2.0/RTI.rid
ENV PATH="${RTI_HOME}/lib:${PATH}"

RUN apt-get update && \
    apt-get install -y --no-install-recommends openjdk-8-jdk
	
	
RUN apt-get install -y --no-install-recommends \
    subversion \
	gcc \
	g++ \
	wget

RUN cd /home/ && \
    wget https://github.com/openlvc/portico/archive/portico-2.1.0.tar.gz && \
	tar -xf portico-2.1.0.tar.gz

COPY ./local.properties /home/portico-portico-2.1.0/codebase

RUN cd /home/portico-portico-2.1.0/codebase && \
    ./ant sandbox && \
    ./ant installer && \
    mv ./dist/portico-2.2.0/ /opt/ && \
    mv ./dist/portico-2.2.0-linux64.tar.gz /opt/portico-2.2.0/
	
WORKDIR /opt/portico-2.2.0

EXPOSE 52295

COPY ./RTI.rid /opt/portico-2.2.0/RTI.rid

RUN rm -rf /home/portico


